from dotenv import load_dotenv
import os

load_dotenv()

# Caminhos host
HOST_ETL_PATH = os.getenv('HOST_ETL_PATH')
HOST_DATA_PATH = os.getenv('HOST_DATA_PATH')
HOST_UTILS_PATH = os.getenv('HOST_UTILS_PATH')
HOST_SPARK_EVENTS_PATH = os.getenv('HOST_SPARK_EVENTS_PATH')
HOST_SPARK_JARS_PATH = os.getenv('HOST_SPARK_JARS_PATH')

# Caminhos container
CONTAINER_ETL_PATH = os.getenv('CONTAINER_ETL_PATH')
CONTAINER_DATA_PATH = os.getenv('CONTAINER_DATA_PATH')
CONTAINER_UTILS_PATH = os.getenv('CONTAINER_UTILS_PATH')
CONTAINER_SPARK_EVENTS_PATH = os.getenv('CONTAINER_SPARK_EVENTS_PATH')
CONTAINER_SPARK_JARS_PATH = os.getenv('CONTAINER_SPARK_JARS_PATH')

# ClickHouse
CLICKHOUSE_HOST = os.getenv('CLICKHOUSE_HOST')
CLICKHOUSE_PORT = os.getenv('CLICKHOUSE_HTTP_PORT')
CLICKHOUSE_USER = os.getenv('CLICKHOUSE_USER')
CLICKHOUSE_PASSWORD = os.getenv('CLICKHOUSE_PASSWORD')
CLICKHOUSE_DATABASE = os.getenv('CLICKHOUSE_DATABASE')