version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_HTTP_PORT}:8123"
      - "${CLICKHOUSE_NATIVE_PORT}:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - dev-sandbox

  clickhouse-init:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    container_name: clickhouse-init
    depends_on:
      - clickhouse
    volumes:
      - ../clickhouse/init-sql:/init-sql
    entrypoint: ["/init-sql/init.sh"]
    networks:
      - dev-sandbox

volumes:
  clickhouse_data:

networks:
  dev-sandbox:
    driver: bridge