version: '3.8'

services:
  etl-runner:
    build:
      context: ../
      dockerfile: dataplataform/docker/etl-runner/Dockerfile
    image: dev-sandbox-etl-runner:latest
    container_name: etl-runner
    ports:
      - "4040:4040"
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - ../dataplataform/scripts:/app/scripts
      - ../dataplataform/utils:/app/utils
      - ../minIo/staging/spark-events:/tmp/spark-events
    command: tail -f /dev/null
    networks:
      - dev-sandbox

networks:
  dev-sandbox:
    driver: bridge